# exercicio
nome = input('seu nome: ')
cpf = input('sey cpf: ')
endereco = input('seu endereço: ')
idade = input('sua idade: ')
altura = input('sua altura: ')
tel = input('seu telefone: ')

print('\n\nseus dados')
print('nome:', nome)
print('cpf:', cpf)
print('endereço:', endereco)
print('idade:', idade)
print('altura', altura)
print('telefone', tel)